# questions.toml

# this is an array of tables
[[questions]]
question = "Which version of Python is the first with TOML support built in"
answers = ["3.11"]
alternatives = ["3.9", "3.10", "3.12"]

[[questions]]
question = "When does __name__ == '__main__' equal True in a Python file"
answers = ["When the file is run as a script"]
alternatives = ["When the file is imported as a module",
                "When the file has a valid name",
                "When the file only has one function",
]

[[questions]]
question = "Which version of Python is the first with TOML support built in"
answers = ["3.11"]
alternatives = ["3.9", "3.10", "3.12"]

[[questions]]
question = "When was the first known use of the word 'quiz'"
answers = ["1781"]
alternatives = ["1771", "1871", "1881"]

[[questions]]
question = "Which built-in function can get information from the user"
answers = ["input"]
alternatives = ["get", "print", "write"]

[[questions]]
question = "Which keyword do you use to loop over a given list of elements"
answers = ["for"]
alternatives = ["while", "each", "loop"]

[[questions]]
question = "What's the purpose of the built-in zip() function"
answers = ["To iterate over two or more sequences at the same time"]
alternatives = ["To combine several strings into one",
                "To compress several files into one archive",
                "To get information from the user"]
[[questions]]
question = "What's one effect of calling renadmo.seed(42)"
answers = ["The random numbers are reproduceable"]
alternatives = ["The random numbers are more random",
                "The computer clock is reset",
                "The first random number is always 42"]

[[questions]]
question = "What is django?"
answers = ["A python web framework"]
alternatives = ["A movie",
                "A candy",
                "nothing"]



[[questions]]
question = "What's the name of the list-like data structure in TOML"
answers = ["Array"]
alternatives = ["List", "Sequence", "Set"]

[[questions]]
question = "How can you run a Python script named quiz.py"
answers = ["python quiz.py", "python -m quiz"]
alternatives = ["python quiz", "python -m quiz.py"]