# questions.toml

"When does __name__ == '__main__' equal True in a Python file" = [
    "When the file is run as a script",
    "When the file is imported as a module",
    "When the file has a valid name",
    "When the file only has one function",
]

"Which version of Python is the first with TOML support built in" = [
    "3.11", "3.9", "3.10", "3.12"
]

"When was the first known use of the word 'quiz'" = [
        "1781", "1771", "1871", "1881"
]

"Which built-in function can get information from the user" =  [
    "input", "get", "print", "write"
]

"Which keyword do you use to loop over a given list of elements" =  [
    "for", "while", "each", "loop"
]

"What's the purpose of the built-in zip() function" =  [
    "To iterate over two or more sequences at the same time",
    "To combine several strings into one",
    "To compress several files into one archive",
    "To get information from the user",
]

"What's one effect of calling renadmo.seed(42)" =  [
    "The random numbers are reproduceable",
    "The random numbers are more random",
    "The computer clock is reset",
    "The first random number is always 42",
]

"What is django?" = [
    "A python web framework",
    "A movie",
    "A candy",
    "nothing",
]

